<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تشخیص اخبار دروغین
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
مطمئنا بارها شنیده‌اید که در فضای مجازی اخبار دروغ و شایعه بسیار رایج است. افرادی هستند که به هر دلیل اقدام به انتشار خبرهای دروغ می‌کنند. برخی این دروغ‌ها از جنس خبرهای سیاسی، اقتصادی یا حواشی راجع به زندگی افراد مشهور و سلبریتی‌هاست. اما به هر نحوی که باشد، دروغ رفتار خوبی نیست.
    <br>
    پس به عنوان یک مخاطب خوب است که بتوانیم تشخیص دهیم چه خبری حقیقت و چه خبری دروغ است. اگر از دید یک خبرگزاری هم به ماجرا نگاه کنیم، متوجه خواهیم شد که اصلا دوست نداریم یک خبر دروغ اقتصادی یا سیاسی از زبان ما منتشر شود؛ در غیر این صورت عواقب پیشبینی‌نشده‌ای در انتظارمان خواهد بود!
    <br>
    پس حال که به اهمیت و کاربرد تشخیص اخبار دروغین پی برده‌ایم، خوب است خودمان تلاش کنیم مدلی آموزش دهیم که خبرهای دروغ را از حقیقت جدا کنیم.
    <br>
    البته تشخیص این امر، وابسته به توانایی پردازش زبان طبیعی است و با دانش یادگیری ماشین کلاسیک، به سادگی نمی‌توان مسئله رو حل کرد. برای اینکه مسئله قابل حل باشد، بخش «پردازش زبان طبیعی» را خود ما انجام داده‌ایم و نتیجه آن‌ را در قالب بخشی از مجموعه‌داده در اختیار شما قرار داده‌ایم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd 
import scipy.sparse as ss

from sklearn.model_selection import train_test_split

from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, f1_score

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
مجموعه‌داده این تمرین، مانند تمرین‌های قبلی به دو مجموعه آموزش و آزمون تقسیم‌بندی می‌شود. اما نکته حائز اهمیت این است که هر کدام از این دو مجموعه آزمون و آموزش، خود دارای دو مجموعه داده است. به عبارت بهتر مجموعه آموزش دارای دو مجموعه‌داده به اسم <code>news_train.csv</code> و <code>news_train_text_vectors.npz</code> است (مجموعه آزمون هم همینطور است).
    <br>
    در فایل <code>news_train.csv</code> اطلاعات کلی مانند زمان انتشار، منبع و برچسب خبر آمده است؛ اما خود خبر را در این مجموعه‌داده نداریم. بلکه خود خبر را می‌توان در فایل <code>news_train_text_vectors.npz</code> جستجو کرد. اما در <code>news_train_text_vectors.npz</code> متن خبر قرار نگرفته است، بلکه به کمک روش‌های پردازش زبان طبیعی، متن هر خبر را به یک بردار ۴۲۱۴۱ المانی تبدیل کرده‌ایم و به ازای هر خبر، یک بردار با ابعاد <code>(42141, 1)</code> وجود دارد.
    <br>
    توضیحات مجموعه‌داده <code>news_train.csv</code> را در جدول زیر می‌توانید مشاهده کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|author|شخصی که متن خبر را نوشته است|
|published|تاریخ و ساعتی که خبر منتشر شده است|
|site_url|سایت منتشرکننده خبر|
|type|برای هر خبر یک دسته یا یک نوعی نیز ذخیره کرده‌ایم. این ستون می‌تواند یکی از مقادیر `bs` به معنی *پرت* یا ‍‍‍‍`conspiracy` به معنی *توطئه آمیز* یا `bias` به معنی *سوگیری یا متعصبانه* یا `hate` به معنی *نفرت‌افکن یا خشم‌آلود* یا ‍`satrie` به معنی *طنز* یا `junksci` به معنی *به درد نخور یا آشغال* و `fake` به معنی *دروغ* باشد|
|label|برچسب خبر را نشان می‌دهد. این ستون یا `Fake` است یا `Real`|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در کنار فایل <code>news_train.csv</code> فایل <code>news_train_text_vectors.npz</code> نیز قرار دارد. کلیات این فایل را در قسمت قبلی توضیح دادیم. به حجیم بودن فایل و صرفه‌جویی درفضای ذخیره‌سازی و کاهش زمان برای بارگذاری فایل، به جای فرمت <code>csv</code> آن را در فرمت <code>npz</code> در اختیار شما قرار دادیم. اما پیشنهاد می‌کنیم برای راحتی خودتان، پس از خواندن فایل، آن را به یک دیتافریم با ۱۵۰۰ سطر و ۴۲۱۴۱ ستون تبدیل کنید.
    <br>
    اینطور در نظر داشته باشید که متن هر خبر را با ۴۲۱۴۱ ویژگی برایتان توصیف کرده‌ایم!
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>news_train.csv</code> و <code>news_train_text_vectors.npz</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>news_test.csv</code> و <code>news_test_text_vectors.npz</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از دادگان آموزشی را به عنوان دادگان اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [259]:
train_data = pd.read_csv('../data/news_train.csv')
train_data_text_vectors = ss.load_npz('../data/news_train_text_vectors.npz')

test_data = pd.read_csv('../data/news_test.csv')
test_data_text_vectors = ss.load_npz('../data/news_test_text_vectors.npz')

In [260]:
x_train = train_data.drop(columns=["label"])
y_train = train_data["label"]

In [261]:
train_data_text_vectors = pd.DataFrame(train_data_text_vectors.toarray())
test_data_text_vectors = pd.DataFrame(test_data_text_vectors.toarray())

In [95]:
train_data["site_url"].value_counts()

prisonplanet.com         89
returnofkings.com        84
awdnews.com              82
infowars.com             82
frontpagemag.com         82
                         ..
barenakedislam.com        1
defenddemocracy.press     1
madworldnews.com          1
allnewspipeline.com       1
davidwolfe.com            1
Name: site_url, Length: 61, dtype: int64

In [23]:
train_data

,author,published,site_url,type,label
0,No Author,2016-11-01T03:28:50.389+02:00,clickhole.com,satire,Fake
1,Anonymous,2016-10-27T21:30:00.000+03:00,abeldanger.net,bs,Fake
2,Kali74,2016-10-27T02:54:49.093+03:00,abovetopsecret.com,bs,Fake
3,Alex Ansary,2016-11-04T22:44:06.026+02:00,amtvmedia.com,bs,Fake
4,Luke Stranahan,2016-11-23T15:10:56.702+02:00,returnofkings.com,hate,Real
...,...,...,...,...,...
1495,Daniel Greenfield,2016-11-02T13:25:57.336+02:00,frontpagemag.com,hate,Real
1496,theeconomiccollapseblog.com,http://theeconomiccollapseblog.com/wp-content/...,theeconomiccollapseblog.com,bs,Fake
1497,Alex Ansary,2016-11-02T19:24:00.901+02:00,amtvmedia.com,bs,Fake
1498,EdJenner,2016-11-22T15:44:03.678+02:00,dailywire.com,bias,Real
1499,No Author,2016-10-29T17:41:00.000+03:00,davidwolfe.com,bs,Fake

In [26]:
train_data.groupby(["author","label"]).count()

,,published,site_url,type
author,label,,,
# 1 NWO Hatr,Fake,2,2,2
-NO AUTHOR-,Real,19,19,19
4 Goals For The Neomasculinity Movement During Trumps First Term,Real,1,1,1
?????? ???? ???? ?????????,Fake,1,1,1
A. Griffee,Fake,2,2,2
...,...,...,...,...
vlawde,Fake,1,1,1
voltairenet.org,Fake,1,1,1
willz,Fake,1,1,1
wmw_admin,Fake,1,1,1
xuenchen,Fake,2,2,2

In [38]:
grouped_1 = train_data.groupby(["site_url", "label"]).count()
grouped_1.reset_index(inplace=True)
grouped_1 = grouped_1.drop(columns=["published","type"])

fromthetrenchesworldreport.com    2
davidduke.com                     2
frontpagemag.com                  2
prisonplanet.com                  2
newstarget.com                    2
                                 ..
davidwolfe.com                    1
dcclothesline.com                 1
defenddemocracy.press             1
dennismichaellynch.com            1
wnd.com                           1
Name: site_url, Length: 61, dtype: int64

In [42]:
grouped_1.columns = ["site_url","label","Number"]

In [46]:
grouped_1

                  site_url label  Number
0      100percentfedup.com  Real      27
1      21stcenturywire.com  Fake      18
2           abcnews.com.co  Fake       2
3           abeldanger.net  Fake      63
4       abovetopsecret.com  Fake      41
..                     ...   ...     ...
64   westernjournalism.com  Fake       2
65   westernjournalism.com  Real      79
66  whatreallyhappened.com  Fake       8
67   whydontyoutrythis.com  Real       2
68                 wnd.com  Real      44

[69 rows x 3 columns]

In [70]:
fake = grouped_1[grouped_1["label"] == "Fake"].groupby("site_url")["Number"].sum().reset_index()
fake.columns = ["site_url","Fake_Number"]
fake

                          site_url  Fake_Number
0              21stcenturywire.com           18
1                   abcnews.com.co            2
2                   abeldanger.net           63
3               abovetopsecret.com           41
4                 activistpost.com           81
5              adobochronicles.com           11
6                    ahtribune.com           52
7              allnewspipeline.com            1
8                 americannews.com            2
9      americasfreedomfighters.com            2
10                       amren.com           35
11                   amtvmedia.com           36
12                     awdnews.com           82
13              barenakedislam.com            1
14                   clickhole.com           71
15              coasttocoastam.com            4
16               corbettreport.com           22
17             countercurrents.org            3
18                counterpunch.org            3
19                     darkmoon.me            8
20                   davidduke.com            1
21  davidstockmanscontracorner.com            7
22                  davidwolfe.com            1
23               dcclothesline.com           32
24           defenddemocracy.press            1
25          dennismichaellynch.com           14
26                     departed.co           11
27  fromthetrenchesworldreport.com           25
28                frontpagemag.com            1
29          galacticconnection.com            4
30               globalresearch.ca            1
31                    infowars.com           82
32              intrepidreport.com            1
33                     legorafi.fr           41
34                madworldnews.com            1
35                 naturalnews.com           81
36                  newstarget.com            4
37                prisonplanet.com           88
38              projectveritas.com            1
39               returnofkings.com            1
40              shiftfrequency.com            9
41             thedailysheeple.com            6
42     theeconomiccollapseblog.com            6
43       thefreethoughtproject.com           11
44                    theonion.com            2
45              thepeoplescube.com            1
46                     thesaker.is            1
47            thetruthseeker.co.uk            1
48                 topinfopost.com            2
49               veteranstoday.com            2
50             washingtonsblog.com            1
51           westernjournalism.com            2
52          whatreallyhappened.com            8

In [73]:
real = grouped_1[grouped_1["label"] == "Real"].groupby("site_url")["Number"].sum().reset_index()
real.columns = ["site_url", "Real_Number"]

In [96]:
merged = real.merge(fake, on="site_url", how="outer")

In [97]:
merged

                          site_url  Real_Number  Fake_Number
0              100percentfedup.com         27.0          NaN
1                addictinginfo.org         19.0          NaN
2                    dailywire.com         64.0          NaN
3                    davidduke.com         31.0          1.0
4   fromthetrenchesworldreport.com          1.0         25.0
..                             ...          ...          ...
56                     thesaker.is          NaN          1.0
57            thetruthseeker.co.uk          NaN          1.0
58                 topinfopost.com          NaN          2.0
59               veteranstoday.com          NaN          2.0
60          whatreallyhappened.com          NaN          8.0

[61 rows x 3 columns]

In [98]:
merged.fillna(0,inplace = True)

In [99]:
merged["Fake_Number"] = merged["Fake_Number"].astype(int)

In [100]:
merged["url_suspicious"] = merged["Real_Number"] < merged["Fake_Number"]

In [101]:
merged

                          site_url  Real_Number  Fake_Number  url_suspicious
0              100percentfedup.com         27.0            0           False
1                addictinginfo.org         19.0            0           False
2                    dailywire.com         64.0            0           False
3                    davidduke.com         31.0            1           False
4   fromthetrenchesworldreport.com          1.0           25            True
..                             ...          ...          ...             ...
56                     thesaker.is          0.0            1            True
57            thetruthseeker.co.uk          0.0            1            True
58                 topinfopost.com          0.0            2            True
59               veteranstoday.com          0.0            2            True
60          whatreallyhappened.com          0.0            8            True

[61 rows x 4 columns]

In [106]:
merged[merged["site_url"] == "100percentfedup.com"]["url_suspicious"]

0    False
Name: url_suspicious, dtype: bool

In [112]:
merged.drop(columns=["Real_Number","Fake_Number"],inplace = True)

In [114]:
merged["url_suspicious"].replace(False,-1,inplace = True)
merged["url_suspicious"].replace(True, 1, inplace=True)

In [110]:
x_train

,author,published,site_url,type
0,No Author,2016-11-01T03:28:50.389+02:00,clickhole.com,satire
1,Anonymous,2016-10-27T21:30:00.000+03:00,abeldanger.net,bs
2,Kali74,2016-10-27T02:54:49.093+03:00,abovetopsecret.com,bs
3,Alex Ansary,2016-11-04T22:44:06.026+02:00,amtvmedia.com,bs
4,Luke Stranahan,2016-11-23T15:10:56.702+02:00,returnofkings.com,hate
...,...,...,...,...
1495,Daniel Greenfield,2016-11-02T13:25:57.336+02:00,frontpagemag.com,hate
1496,theeconomiccollapseblog.com,http://theeconomiccollapseblog.com/wp-content/...,theeconomiccollapseblog.com,bs
1497,Alex Ansary,2016-11-02T19:24:00.901+02:00,amtvmedia.com,bs
1498,EdJenner,2016-11-22T15:44:03.678+02:00,dailywire.com,bias
1499,No Author,2016-10-29T17:41:00.000+03:00,davidwolfe.com,bs

In [116]:
x_train = x_train.merge(merged, on="site_url", how="outer")

In [128]:
x_train

,author,published,site_url,type,url_suspicious
0,No Author,2016-11-01T03:28:50.389+02:00,clickhole.com,satire,1
1,No Author,2016-11-11T17:42:00.000+02:00,clickhole.com,satire,1
2,No Author,2016-11-12T02:14:05.550+02:00,clickhole.com,satire,1
3,No Author,2016-11-14T21:18:48.016+02:00,clickhole.com,satire,1
4,No Author,2016-11-02T21:07:00.000+02:00,clickhole.com,satire,1
...,...,...,...,...,...
1495,Mike Rivero,2016-11-19T23:33:00.000+02:00,whydontyoutrythis.com,bias,-1
1496,Mike Rivero,2016-11-21T03:44:07.262+02:00,whydontyoutrythis.com,bias,-1
1497,Mikael Thalen,2016-10-29T13:10:20.545+03:00,intrepidreport.com,satire,1
1498,Madeline,2016-10-26T22:09:20.070+03:00,globalresearch.ca,conspiracy,1
1499,No Author,2016-10-29T17:41:00.000+03:00,davidwolfe.com,bs,1

In [131]:
grouped_2 = train_data.groupby(["author", "label"]).count()
grouped_2.reset_index(inplace=True)
grouped_2 = grouped_2.drop(columns=["published", "type"])
grouped_2.columns = ["author", "label", "Number"]

In [137]:
grouped_2[grouped_2["author"] == "# 1 NWO Hatr"]

         author label  Number
0  # 1 NWO Hatr  Fake       2

In [135]:
fake_author = (grouped_2[grouped_2["label"] == "Fake"].groupby("author")["Number"].sum().reset_index())
fake_author.columns = ["author", "Fake_Number"]
fake_author

                         author  Fake_Number
0                  # 1 NWO Hatr            2
1    ?????? ???? ???? ?????????            1
2                    A. Griffee            2
3                   AFRICA-NEWS            1
4                 Activist Post           64
..                          ...          ...
254                      vlawde            1
255             voltairenet.org            1
256                       willz            1
257                   wmw_admin            1
258                    xuenchen            2

[259 rows x 2 columns]

In [139]:
real_author = (grouped_2[grouped_2["label"] == "Real"].groupby("author")["Number"].sum().reset_index())
real_author.columns = ["author", "Real_Number"]
real_author

                                                author  Real_Number
0                                          -NO AUTHOR-           19
1    4 Goals For The Neomasculinity Movement During...            1
2                                         Aaron Clarey            1
3                              About Daniel Greenfield            1
4                                      Adalia Woodbury            1
..                                                 ...          ...
163                                  Wanda Freeman Lay            1
164                                    WashingtonsBlog            1
165               Why Do People Become Cuckservatives?            1
166                             Yrag Werdna Xuaedobiht            1
167                               reasoning with facts            1

[168 rows x 2 columns]

In [140]:
merged_author = real_author.merge(fake_author, on="author", how="outer")

In [142]:
merged_author.fillna(0, inplace=True)

In [145]:
merged_author["author_suspicious"] = (merged_author["Real_Number"] < merged_author["Fake_Number"])

In [147]:
merged_author.drop(columns=["Real_Number", "Fake_Number"], inplace=True)

In [149]:
merged_author["author_suspicious"].replace(False, -1, inplace=True)
merged_author["author_suspicious"].replace(True, 1, inplace=True)

In [157]:
merged_author["author_suspicious"].value_counts()

 1    253
-1    165
Name: author_suspicious, dtype: int64

In [151]:
x_train = x_train.merge(merged_author, on="author", how="outer")

In [154]:
merged[merged["site_url"] == "clickhole.com"]

         site_url  url_suspicious
30  clickhole.com               1

In [156]:
x_train["author_suspicious"].value_counts()

 1    1037
-1     463
Name: author_suspicious, dtype: int64

In [163]:
x_train[(x_train["author_suspicious"] == 1) & (x_train["url_suspicious"] == -1)]

,author,published,site_url,type,url_suspicious,author_suspicious
71,No Author,2016-11-02T07:05:45.847+02:00,returnofkings.com,hate,-1,1
98,No Author,2016-11-05T03:00:36.461+02:00,dailywire.com,bias,-1,1
99,No Author,2016-11-21T21:18:43.762+02:00,dailywire.com,bias,-1,1
100,No Author,2016-11-11T03:38:00.000+02:00,dailywire.com,bias,-1,1
101,No Author,2016-11-22T16:37:31.350+02:00,dailywire.com,bias,-1,1
...,...,...,...,...,...,...
750,Matthew Everett,2016-10-26T22:46:58.887+03:00,westernjournalism.com,bs,-1,1
1090,Mike Rivero,2016-11-19T23:33:00.000+02:00,whydontyoutrythis.com,bias,-1,1
1091,Mike Rivero,2016-11-21T03:44:07.262+02:00,whydontyoutrythis.com,bias,-1,1
1163,Don Wrightman,2016-11-23T22:47:00.000+02:00,politicususa.com,bias,-1,1
1486,voltairenet.org,2016-10-27T03:00:00.000+03:00,washingtonsblog.com,bs,-1,1

In [167]:
x_train["type"].value_counts()

bs            423
conspiracy    358
bias          315
hate          197
satire        112
junksci        82
fake           13
Name: type, dtype: int64

In [169]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x_train["type"] = label_encoder.fit_transform(x_train["type"])
x_train

,author,published,site_url,type,url_suspicious,author_suspicious
0,No Author,2016-11-01T03:28:50.389+02:00,clickhole.com,6,1,1
1,No Author,2016-11-11T17:42:00.000+02:00,clickhole.com,6,1,1
2,No Author,2016-11-12T02:14:05.550+02:00,clickhole.com,6,1,1
3,No Author,2016-11-14T21:18:48.016+02:00,clickhole.com,6,1,1
4,No Author,2016-11-02T21:07:00.000+02:00,clickhole.com,6,1,1
...,...,...,...,...,...,...
1495,Starkman,2016-10-28T04:27:38.678+03:00,veteranstoday.com,1,1,1
1496,wmw_admin,2016-10-31T14:04:35.283+02:00,topinfopost.com,1,1,1
1497,Pankaj Vaidya,2016-10-29T08:35:06.031+03:00,topinfopost.com,1,1,1
1498,Brendan,2016-10-26T16:41:00.000+03:00,projectveritas.com,1,1,1
1499,The Saker,2016-11-05T23:45:02.270+02:00,thetruthseeker.co.uk,1,1,1

In [171]:
x_train.drop(columns=["author","published","site_url"],inplace = True)
x_train

      type  url_suspicious  author_suspicious
0        6               1                  1
1        6               1                  1
2        6               1                  1
3        6               1                  1
4        6               1                  1
...    ...             ...                ...
1495     1               1                  1
1496     1               1                  1
1497     1               1                  1
1498     1               1                  1
1499     1               1                  1

[1500 rows x 3 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
    <br>
    از آنجایی که قرار است در این تمرین از الگوریتم ماشین بردار پشتیبان استفاده کنید، حتما باید مجموعه‌داده <code>news_train_text_vectors.npz</code> را با روش‌های کاهش ابعادی که یاد گرفته‌اید، به نحوی تغییر دهید که در زمان معقولی توسط الگوریتم <code>svm</code> پردازش شود. اگر چه الگوریتمی که برای کاهش ابعاد استفاده می‌کنید در کوئرا بررسی نمی‌شود، اما پیشنهاد ما استفاده از <code>PCA</code> است. آنچه اهمیت دارد آن است که بین کوچک‌کردن داده و کیفیت مدل تعادل برقرار کنید. طبیعی است که هرچقدر داده کوچک‌تر باشد، احتمالا الگوریتم ماشین بردار پشتیبان زودتر به نتیجه می‌رسد؛ اما در نظر داشته باشید با کاهش بعد، شما عملا بخشی از داده را از دست می‌دهید!
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    الگوریتم <i>تحلیل مولفه‌های اصلی</i> با نام <code>PCA</code> در پکیج <code>decomposition</code> این کتابخانه در دسترس است. برخی از آرگومان‌های مهم آن در جدول زیر آمده است، اما جهت مطالعه‌ی کامل‌تر مستندات می‌توانید به <a href="https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html" target="_blank">این لینک</a> مراجعه فرمایید.
    <br>
    برای استفاده از این الگوریتم، می‌توانید با اجرای <code>from sklearn.decomposition import PCA</code> آن را وارد (<code>import</code>) کنید.
    <br>
    
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

|آرگومان|جنس و تایپ|توضیحات|
|:------:|:--------:|:---:|
|n_components|<code>int</code> یا <code>float</code>|تعداد مولفه‌هایی است که قصد داریم پس از اجرای الگوریتم، آن‌ها را داشته باشیم و حذف نشوند. اگر به این آرگومان مقدار ندهیم، همه مولفه‌ها حفظ خواهند شد. اگر جنس این آرگومان <code>int</code> باشد، نشانگر تعداد مولفه‌هایی است که قصد داریم حفظ شود. اما اگر از جنس <code>float</code> و به شکل $0< n\_components< 1$ باشد، به این معنا خواهد بود که به اندازه‌ای از مولفه‌ها حفظ شوند که واریانس داده‌ها بزرگتر از `n_componets`٪ باشد. بنابراین می‌توان اینگونه برداشت کرد که هرچه این عدد به ۱ نزدیک‌تر باشد، چون قرار است داده واریانس زیادی داشته باشد، پس مولفه‌های بیشتری حفظ می‌شوند.|
    
</font>
</div>
</center>



<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    کلاس <code>PCA</code> دارای سه متد به شرح زیر است: 
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|اسم متد|توضیحات|
|:------:|:---:|
|fit(X)|الگوریتم را با X که در ابعاد `(n_samples, n_features)` است|
|transform(X)|این تابع X که از ابعاد `(n_samples, n_features)` است را به یک ماتریس دیگری با ابعاد `(n_samples, n_components)` تبدیل می‌کند. پس خروجی این تابع یک ماتریس به ابعاد `(n_samples, n_components)` خواهد بود|
|fit_transform(X)|ابتدا تابع <code>fit</code> و سپس تابع <code>transform</code> را اجرا می‌کند|
</font>
</div>
</center>

In [ ]:
# Preprocessing

In [298]:
dr = PCA(n_components=500)
reduced_train_text_vectors = dr.fit_transform(train_data_text_vectors)
reduced_test_text_vectors = dr.transform(test_data_text_vectors)

In [299]:
reduced_train_text_vectors_table = pd.DataFrame(reduced_train_text_vectors)
reduced_test_text_vectors_table = pd.DataFrame(reduced_test_text_vectors)

In [300]:
model2 = SVC()
model2.fit(reduced_train_text_vectors, y_train)

SVC()

In [301]:
y_pred_train1 = model2.predict(reduced_train_text_vectors)
y_pred_test1 = model2.predict(reduced_test_text_vectors)

In [302]:
y_pred_train1 = pd.DataFrame(y_pred_train1,columns=["text_suspecious"])
y_pred_test1 = pd.DataFrame(y_pred_test1, columns=["text_suspecious"])

In [303]:
y_pred_train1.replace("Fake",1,inplace=True)
y_pred_train1.replace("Real", -1, inplace=True)

y_pred_test1.replace("Fake", 1, inplace=True)
y_pred_test1.replace("Real", -1, inplace=True)

In [304]:
x_train_new = pd.concat([y_pred_train1, train_data["type"]],axis = 1)
x_test_new = pd.concat([y_pred_test1, test_data["type"]], axis=1)

In [305]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x_train_new["type"] = label_encoder.fit_transform(x_train_new["type"])
x_test_new["type"] = label_encoder.transform(x_test_new["type"])
x_test_new

     text_suspecious  type
0                 -1     0
1                  1     6
2                 -1     0
3                 -1     0
4                  1     4
..               ...   ...
341                1     6
342               -1     0
343                1     1
344                1     2
345                1     6

[346 rows x 2 columns]

In [306]:
model = SVC()
model.fit(x_train_new,y_train)
y_pred_train = model.predict(x_train_new)
y_pred_test = model.predict(x_test_new)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
    <br>
    <b>توجه داشته باشید که برای پیشبینی متغیر هدف این مسئله حتما باید از الگوریتم <code>SVM</code> استفاده کنید. در غیر این صورت، نمره‌ای دریافت نخواهید کرد.</b>
    <br>
    نحوه استفاده از این الگوریتم را در تمرین‌ها و درسنامه‌های قبلی آموخته‌اید.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h3>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی دادگان آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>80</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

In [307]:
# Evaluation
from sklearn.metrics import f1_score
f1_score(y_pred_train, y_train, pos_label="Fake")

0.9933774834437086

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|------|---|
|label|برچسب پیشبینی شده|
    
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اسم دیتافریم باید <i>submission</i> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل ۱ ستون با اسم <i>label</i> است و ۳۴۶ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، اعداد ستون <i>label</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||label|
|----|-----|
|0|Fake|
|1|Fake|
|2|Real|
|3|Fake|
|4|Real|
</font>
</div>

In [308]:
submission = pd.DataFrame(y_pred_test,columns=["label"])
submission

    label
0    Real
1    Fake
2    Real
3    Real
4    Real
..    ...
341  Fake
342  Real
343  Fake
344  Fake
345  Fake

[346 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [309]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

joblib.dump(model, 'model')
submission.to_csv('submission.csv', index=False)
file_names = ['fake_news_detection.ipynb', 'submission.csv', 'model']
compress(file_names)

File Paths:
['fake_news_detection.ipynb', 'submission.csv', 'model']